codecov:
  notify:
    after_n_builds: 10
comment:
  after_n_builds: 10
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto
        informational: false
    patch:
      default:
        target: auto
        threshold: 100%
        base: auto
github_checks:
    annotations: false