//! This module defines the messages communicated between the parties(Taker, Maker)
use crate::protocol::messages::FidelityProof;
use bitcoin::{Amount, PublicKey, ScriptBuf, Txid};
use secp256k1::musig::{PartialSignature, PublicNonce};
use serde::{Deserialize, Serialize};
use std::{convert::TryInto, fmt::Display};

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
/// Serializable wrapper for secp256k1 PublicNonce
pub struct SerializablePublicNonce(pub Vec<u8>);

/// Defines the length of the Preimage.
pub(crate) const PREIMAGE_LEN: usize = 32;

/// Type for Preimage.
pub(crate) type Preimage = [u8; PREIMAGE_LEN];

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
/// Serializable wrapper for secp256k1 Scalar
pub struct SerializableScalar(pub Vec<u8>);

impl From<PublicNonce> for SerializablePublicNonce {
    fn from(nonce: PublicNonce) -> Self {
        SerializablePublicNonce(nonce.serialize().to_vec())
    }
}

impl From<SerializablePublicNonce> for PublicNonce {
    fn from(nonce: SerializablePublicNonce) -> Self {
        let bytes: [u8; 66] = nonce.0.try_into().expect("invalid nonce value");
        PublicNonce::from_byte_array(&bytes).expect("invalid nonce value")
    }
}

impl From<bitcoin::secp256k1::Scalar> for SerializableScalar {
    fn from(scalar: bitcoin::secp256k1::Scalar) -> Self {
        SerializableScalar(scalar.to_be_bytes().to_vec())
    }
}

impl From<SerializableScalar> for bitcoin::secp256k1::Scalar {
    fn from(scalar: SerializableScalar) -> Self {
        let bytes: [u8; 32] = scalar.0.try_into().expect("invalid scalar length");
        bitcoin::secp256k1::Scalar::from_be_bytes(bytes).expect("invalid scalar value")
    }
}

// Note: Nonces should be generated using proper MuSig2 procedures with transaction context,
// not converted from arbitrary secret keys

impl Display for TakerToMakerMessage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::GetOffer(_) => write!(f, "GetOffer"),
            Self::SwapDetails(_) => write!(f, "SwapDetails"),
            Self::SendersContract(_) => write!(f, "SendersContract"),
            Self::PrivateKeyHandover(_) => write!(f, "PrivateKeyHandover"),
        }
    }
}

impl Display for MakerToTakerMessage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::RespOffer(_) => write!(f, "RespOffer"),
            Self::AckResponse(_) => write!(f, "AckResponse"),
            Self::SenderContractFromMaker(_) => write!(f, "SenderContractFromMaker"),
            Self::PrivateKeyHandover(_) => write!(f, "PrivateKeyHandover"),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
/// Serializable wrapper for secp256k1 PartialSignature
pub struct SerializablePartialSignature(pub Vec<u8>);

impl From<PartialSignature> for SerializablePartialSignature {
    fn from(sig: PartialSignature) -> Self {
        SerializablePartialSignature(sig.serialize().to_vec())
    }
}

impl From<SerializablePartialSignature> for PartialSignature {
    fn from(sig: SerializablePartialSignature) -> Self {
        let bytes: [u8; 32] = sig.0.try_into().expect("invalid signature value");
        PartialSignature::from_byte_array(&bytes).expect("invalid signature value")
    }
}

/// Private key handover message exchanged during taproot coinswap sweeps
///
/// After contract transactions are established and broadcasted, parties exchange
/// their outgoing contract private keys to enable independent sweeping without
/// requiring MuSig2 coordination.
#[derive(minicbor::Encode, minicbor::Decode, Debug, Serialize, Deserialize, Clone)]
pub struct PrivateKeyHandover {
    /// Unique 8 byte ID to identify each swap process separately. Always generated by the Takers.
    #[n(0)]
    pub(crate) id: String,
    /// The outgoing contract private key
    #[n(1)]
    #[cbor(encode_with = "encode_secret_key", decode_with = "decode_secret_key")]
    pub(crate) secret_key: bitcoin::secp256k1::SecretKey,
}

#[derive(minicbor::Encode, minicbor::Decode, Debug, Clone, Serialize, Deserialize)]
#[allow(clippy::large_enum_variant)]
pub(crate) enum TakerToMakerMessage {
    #[n(0)]
    GetOffer(#[n(0)] GetOffer),
    #[n(1)]
    SwapDetails(#[n(0)] SwapDetails),
    #[n(2)]
    SendersContract(#[n(0)] SendersContract),
    #[n(3)]
    PrivateKeyHandover(#[n(0)] PrivateKeyHandover),
}

#[derive(minicbor::Encode, minicbor::Decode, Debug, Serialize, Deserialize)]
pub(crate) enum MakerToTakerMessage {
    #[n(0)]
    RespOffer(#[n(0)] Box<Offer>),
    #[n(1)]
    AckResponse(#[n(0)] AckResponse),
    #[n(2)]
    SenderContractFromMaker(#[n(0)] SenderContractFromMaker),
    #[n(3)]
    PrivateKeyHandover(#[n(0)] PrivateKeyHandover),
}

#[derive(minicbor::Encode, minicbor::Decode, Debug, Clone, Serialize, Deserialize)]
pub(crate) struct GetOffer {
    #[n(0)]
    pub(crate) protocol_version_min: u32,
    #[n(1)]
    pub(crate) protocol_version_max: u32,
    #[n(2)]
    pub(crate) number_of_transactions: u32,
}

/// An offer from a maker to participate in a coinswap
#[derive(minicbor::Encode, minicbor::Decode, Debug, Serialize, Deserialize, Clone)]
pub struct Offer {
    /// The tweakable public key for the maker
    #[n(0)]
    #[cbor(encode_with = "encode_public_key", decode_with = "decode_public_key")]
    pub tweakable_point: PublicKey,
    /// Base fee charged by the maker (in satoshis)
    #[n(1)]
    pub base_fee: u64,
    /// Fee as a percentage relative to the swap amount
    #[n(2)]
    pub amount_relative_fee: f64,
    /// Fee as a percentage relative to the time lock duration
    #[n(3)]
    pub time_relative_fee: f64,
    /// Minimum time lock duration required by the maker
    #[n(4)]
    pub minimum_locktime: u16,
    /// Fidelity proof demonstrating the maker's commitment
    #[n(5)]
    pub fidelity: FidelityProof,
    /// Minimum swap amount the maker will accept (in satoshis)
    #[n(6)]
    pub min_size: u64,
    /// Maximum swap amount the maker can handle (in satoshis)
    #[n(7)]
    pub max_size: u64,
}

#[derive(minicbor::Encode, minicbor::Decode, Debug, Clone, Serialize, Deserialize)]
pub(crate) struct SwapDetails {
    #[n(0)]
    pub(crate) id: String,
    #[n(1)]
    #[cbor(encode_with = "encode_amount", decode_with = "decode_amount")]
    pub(crate) amount: Amount,
    #[n(2)]
    pub(crate) no_of_tx: u8,
    #[n(3)]
    pub(crate) timelock: u16,
}

/// `tweakable_point = Some(_)` → swap accepted (Ack)
/// `tweakable_point = None`    → swap rejected (Nack)
#[derive(minicbor::Encode, minicbor::Decode, Debug, Serialize, Deserialize)]
pub(crate) struct AckResponse {
    #[n(0)]
    #[cbor(
        encode_with = "encode_opt_public_key",
        decode_with = "decode_opt_public_key"
    )]
    pub tweakable_point: Option<PublicKey>,
}

#[derive(minicbor::Encode, minicbor::Decode, Debug, Serialize, Deserialize, Clone)]
pub(crate) struct SendersContract {
    #[n(0)]
    pub(crate) id: String,
    #[n(1)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")] // quick fix
    pub(crate) contract_txs: Vec<Txid>,
    // Below data is used to verify transaction
    #[n(2)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) pubkeys_a: Vec<PublicKey>,
    #[n(3)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) hashlock_scripts: Vec<ScriptBuf>,
    #[n(4)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) timelock_scripts: Vec<ScriptBuf>,
    // Tweakable point for allowing maker to create next contract
    #[n(5)]
    #[cbor(encode_with = "encode_public_key", decode_with = "decode_public_key")]
    pub(crate) next_party_tweakable_point: bitcoin::PublicKey,
    // MuSig2 data for cooperative spending
    #[n(6)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) internal_key: Option<bitcoin::secp256k1::XOnlyPublicKey>,
    #[n(7)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) tap_tweak: Option<SerializableScalar>,
}

#[derive(minicbor::Encode, minicbor::Decode, Debug, Serialize, Deserialize)]
pub(crate) struct SenderContractFromMaker {
    #[n(1)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")] // quick fix
    pub(crate) contract_txs: Vec<Txid>,
    // Below data is used to verify transaction
    #[n(2)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) pubkeys_a: Vec<PublicKey>,
    #[n(3)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) hashlock_scripts: Vec<ScriptBuf>,
    #[n(4)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) timelock_scripts: Vec<ScriptBuf>,
    // MuSig2 data for cooperative spending
    #[n(6)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) internal_key: Option<bitcoin::secp256k1::XOnlyPublicKey>,
    #[n(7)]
    #[cbor(encode_with = "encode_json_bytes", decode_with = "decode_json_bytes")]
    pub(crate) tap_tweak: Option<SerializableScalar>,
}

/// Mempool transaction
#[derive(Serialize, Deserialize, Debug)]
pub struct MempoolTx {
    /// Txid of the transaction spending the utxo
    pub txid: String,
    /// Hex encoded raw transaction
    pub rawtx: String,
}

// Inline minicbor helpers
#[allow(dead_code)]
fn encode_json_bytes<T: serde::Serialize, W: minicbor::encode::Write, C>(
    x: &T,
    e: &mut minicbor::Encoder<W>,
    _ctx: &mut C,
) -> Result<(), minicbor::encode::Error<W::Error>> {
    e.bytes(&serde_json::to_vec(x).map_err(|_| minicbor::encode::Error::message("json error"))?)?;
    Ok(())
}
fn decode_json_bytes<T: serde::de::DeserializeOwned, C>(
    d: &mut minicbor::Decoder<'_>,
    _ctx: &mut C,
) -> Result<T, minicbor::decode::Error> {
    serde_json::from_slice(d.bytes()?)
        .map_err(|_| minicbor::decode::Error::message("json decode error"))
}

fn encode_amount<W: minicbor::encode::Write, C>(
    x: &bitcoin::Amount,
    e: &mut minicbor::Encoder<W>,
    _ctx: &mut C,
) -> Result<(), minicbor::encode::Error<W::Error>> {
    e.u64(x.to_sat())?;
    Ok(())
}
fn decode_amount<C>(
    d: &mut minicbor::Decoder<'_>,
    _ctx: &mut C,
) -> Result<bitcoin::Amount, minicbor::decode::Error> {
    Ok(bitcoin::Amount::from_sat(d.u64()?))
}

fn encode_public_key<W: minicbor::encode::Write, C>(
    x: &bitcoin::PublicKey,
    e: &mut minicbor::Encoder<W>,
    _ctx: &mut C,
) -> Result<(), minicbor::encode::Error<W::Error>> {
    e.encode(x.to_string())?;
    Ok(())
}
fn decode_public_key<C>(
    d: &mut minicbor::Decoder<'_>,
    _ctx: &mut C,
) -> Result<bitcoin::PublicKey, minicbor::decode::Error> {
    let s = d.decode::<String>()?;
    std::str::FromStr::from_str(&s)
        .map_err(|_| minicbor::decode::Error::message("invalid public key"))
}

fn encode_secret_key<W: minicbor::encode::Write, C>(
    x: &bitcoin::secp256k1::SecretKey,
    e: &mut minicbor::Encoder<W>,
    _ctx: &mut C,
) -> Result<(), minicbor::encode::Error<W::Error>> {
    e.bytes(&x.secret_bytes())?;
    Ok(())
}
fn decode_secret_key<C>(
    d: &mut minicbor::Decoder<'_>,
    _ctx: &mut C,
) -> Result<bitcoin::secp256k1::SecretKey, minicbor::decode::Error> {
    bitcoin::secp256k1::SecretKey::from_slice(d.bytes()?)
        .map_err(|_| minicbor::decode::Error::message("invalid secret key"))
}

fn encode_opt_public_key<W: minicbor::encode::Write, C>(
    x: &Option<bitcoin::PublicKey>,
    e: &mut minicbor::Encoder<W>,
    _ctx: &mut C,
) -> Result<(), minicbor::encode::Error<W::Error>> {
    if let Some(pk) = x {
        e.encode(pk.to_string())?;
    } else {
        e.null()?;
    }
    Ok(())
}
fn decode_opt_public_key<C>(
    d: &mut minicbor::Decoder<'_>,
    _ctx: &mut C,
) -> Result<Option<bitcoin::PublicKey>, minicbor::decode::Error> {
    if d.datatype()? == minicbor::data::Type::Null {
        d.null()?;
        return Ok(None);
    }
    let s = d.decode::<String>()?;
    let pk = std::str::FromStr::from_str(&s)
        .map_err(|_| minicbor::decode::Error::message("invalid opt public key"))?;
    Ok(Some(pk))
}
